### ISSUE TITLE
Implement command cooldowns using cinch-cooldown

### ISSUE THREAD

**Issue by rikai** [rikai/Showbot#40]
This is something i'd like implemented before the next release, probably the highest priority thing in the queue...

The blocker issue is described [here](https://github.com/bhaberer/cinch-cooldown/issues/1)
##

**Comment by s0ph0s-2** [comment]
I've narrowed down the issue to [this function](https://github.com/bhaberer/cinch-cooldown/blob/master/lib/cinch/plugin/cooldowns.rb#L12). The middle argument, `shared`, seems to be expecting something other than what it's getting, which causes the `unless` on line 18 to fail, stopping it from triggering. More work to come…

**Comment by s0ph0s-2** [comment]
It turns out that some part of Showbot is changing the YAML interpreter's behavior to always use symbols for keys. As such, the channel names in the YAML config become `:"#channel"`, not just `"#channel"`, so the cinch-cooldown plugin thinks the configuration file is broken and doesn't do anything. A workaround function that loops through the hash and converts the channel keys back to strings does properly make it limit command use.  
Tomorrow, I'll either figure out how to either undo the thing that's breaking the YAML behavior, or submit a change upstream that papers over it.

**Comment by s0ph0s-2** [comment]
[This function](https://github.com/netfeed/cinchize/blob/master/lib/cinchize.rb#L154) is being called recursively on the config Hash, which converts all keys to symbols for faster access. Unfortunately, this wrecks cinch-cooldown's configuration settings, which depend on string keys.

**Comment by s0ph0s-2** [comment]
[PR submitted](https://github.com/bhaberer/cinch-cooldown/issues/6), pending approval.

**Comment by s0ph0s-2** [comment]
bhaberer has expressed a concern that converting the keys back to strings if Cinchize is loaded is kind of a crufty way of fixing it. He is considering updating `cinch-cooldown` to 1.2.0 and expecting symbols internally.

**Comment by rikai** [comment]
@s0ph0s-2 Ceems that cinch-cooldown has been updated with the changes we need, hopefully should be smooth sailing now! :+1:

**Comment by s0ph0s-2** [comment]
Great!

**Comment by rikai** [comment]
@s0ph0s-2 Hoping to get this knocked out sometime soon if you get a chance to look at it. :)

**Comment by s0ph0s-2** [comment]
I took a look during a hackathon in November, but I wasn't able to get it quite finished. I'm in the thick of the spring semester right now, though, so I won't be able to finish it until the end of May.

**Comment by s0ph0s-2** [comment]
This is bizarre. I don't know what magic I was doing earlier to get it to rate-limit properly — it certainly isn't doing it now.   
The monkey-patched hook that `cinch-cooldown` runs before each message is running, but the function it calls to determine if a cooldown needs to be applied doesn't seem to be. I can't tell whether that's because I'm loading the plugin in a non-standard way (for testing), or if it's because `cinchize` is breaking something.

**Comment by s0ph0s-2** [comment]
Aha! I've found the problem. `cinch-cooldown` was never updated on rubygems.org, so the fix was never propagated.  
[Relevant issue on `cinch-cooldown`](https://github.com/bhaberer/cinch-cooldown/issues/7).

**Comment by s0ph0s-2** [comment]
Still waiting on @ bhaberer to update the version on rubygems.org.

**Comment by rikai** [comment]
No worries, looks like he plans to get to it tonight!

**Comment by s0ph0s-2** [comment]
Okay, the changes have been pushed to rubygems.org. I've tested, and things seem to be working properly.  

Now, there are two more questions:
1. What plugins should have cool downs enabled? All of them?
2. What should the cool down values be?

**Comment by s0ph0s-2** [comment]
Relevant IRC conversation:

```
22:33 <~rikai> s0ph0s: if i'm being honest, i'm not sure in respsnse to your questions... I think that most plugins, perhaps with the exception of !suggest, should have cooldowns. Suggest has a high rate of usage at some points, so i'm not sure it should have a cooldown, and it isn't tha spammy... i imagine most others probably need it though...
22:35 <s0ph0s> Okay. Should I guess at the cooldown times from the channel modes then? As with the other anti-spam measure, we can always tweak the numbers if they're not working.
22:39 <~rikai> Guess a best guess is better than nothing, can always tweak from there
22:39 <s0ph0s> Okay then! I'll stick the two lines necessary to enable cinch-cooldown into all of the relevant plugins.
```

**Comment by s0ph0s-2** [comment]
I've omitted both `suggest.rb` and `admin.rb` from the cooldowns, since both of those should respond ASAP.
